title: 完成图3.5：细胞因子释放水平降低
area: research
objective: okr-2025Q4-research
project: proj-thesis-first_draft
status: done
importance: P1
difficulty: 5
duration_minutes: 120
tags: []
time_logs:
- start: 周三_2025-12-24_08:12
  end: 周三_2025-48-24_09:48
  note:
  - 完成Elisa统计方式流程的开发，目前进行到检查标准曲线拟合流程
  - 确定原因是因为数值落在拟合曲线之外所以无法计算，要么更改拟合方法，要么代入其他标准曲线。首选代入其他标准曲线，因为这样结果更接近现实。
- start: 周三_2025-59-24_17:00
  end: 周三_2025-59-24_17:59
  note:
  - 更改拟合方法，使用excel的2次方程拟合，做图后看数据是否符合要求，按需要增加异常值矫正
  - 目前完成了统计方法与验证，接下来需要增加异常值矫正到脚本中，并且验证结果是否正确
- start: 周四_2025-37-25_07:37
  end: 周四_2025-11-25_10:45
  note:
  - 增加异常值矫正到脚本中，并且验证结果是否正确,然后建立做图脚本
  - 完成，接下来需要将数据填满，然后兼容多组数据模式，然后挑选合适数据上图
  - 完成体系建立，并完成e12录入
  - 接下来需要完成后续实验的数据录入
- start: 周一_2025-09-29_08:40
  end: 周一_2025-36-29_10:36
  note:
  - 根据one note中记载的elisa实验记录，将原始数据录入汇总表格中
- start: 周二_2025-09-30_07:39
  end: 周二_2025-28-30_10:28
  note:
  - 首先计划接下来一个月的书写计划，每天完成2张图的进度比较合适
  - 由于时间压力，首先需要完成初稿。先搁置原始数据录入，系统性生成图，然后进行描述
  - 完成图像生成，接下来完成描述，并生成下一张图
- start: 周二_2025-28-30_11:30
  end: 周二_2025-28-30_14:00
  note:
  - 完成
created_at: '2025-09-24T00:12:27+00:00'
due: '2025-10-01'
uid: 2f464fc1
project_uid: da038aa1
objective_uid: df290bef
area_uid: 74a241b3
start: '2025-10-01T00:00:00'
end: '2025-10-01T02:00:00'
duration: 2h
