uid: 6ef3687e
title: 填写冻精申请
status: done
due: '2025-11-07'
start: '2025-11-07T10:00:00'
end: '2025-11-07T11:00:00'
duration: 60min
project_uid: 135efa63
objective_uid: 3a986ba1
area_uid: 74a241b3
acceptance_criteria: []
deliverable: []
repeat_cycle: 不重复
created_at: '2025-10-22'
time_logs: []
completed_at: '2025-10-22T12:31:13'
time_spent_min: 0
