uid: 8e6e4a11
title: 机制瓶颈指标体系构建
status: done
due: '2025-11-19'
start: '2025-11-19T06:00:00'
end: '2025-11-19T08:00:00'
duration: 2h
project_uid: 81988ed4
objective_uid: ae37276e
area_uid: 74a241b3
acceptance_criteria: []
deliverable: []
repeat_cycle: 不重复
created_at: '2025-10-21'
time_logs:
- start: '2025-11-17T16:47:11'
  end: '2025-11-17T16:49:38'
  note: 
    目前已经完成基础概念与数值的创建，需要明确目前无法做到完美，所以就以这个数值为基础进行。为了让整个流程流畅，需要从头修改，将“多批次共同效应”脚本更改为“多批次同时处理”脚本，然后输出不同的文件，之后再进行批次矫正与多组学合并。进行多组学合并之前，先将概念搞清楚，然后建立配置文件，最后建立脚本
- start: '2025-11-18T06:01:47'
  end: '2025-11-20T07:39:15'
  note: "制定多批次同时处理方案——脂质组只需要用批次间矫正前的文件进行处理就行，不需要多批次同时处理方案\n完成脚本流程修改\n根据目的建立配置文件——完成\n\
    根据配置文件与源文件建立脚本，开始进行映射——完成脂质部分\n在完成的同时要完成文章的撰写，以一个结果小模块为一个文件，包含内容有哪些？\n"
completed_at: '2025-11-20T07:39:15'
time_spent_min: 2979
