id: _
uid: 7dc7188d
title: 鼠房整理
status: todo
due: '2025-11-07'
start: '2025-11-07T17:00:00'
end: '2025-11-07T18:00:00'
duration: 60min
project_uid: c82f11bb
objective_uid: ea77a793
area_uid: e9a4dfa8
acceptance_criteria: []
deliverable: []
repeat_cycle: 每周
created_at: '2025-10-30'
repeat_rule:
  freq: weekly
  interval: 2
  byweekday:
  - 3
repeat_due: '2026-10-30'
