id: __4701
uid: 4701ee02
title: 基因型标注、冻精申请
status: done
due: '2025-11-14'
start: '2025-11-14T10:30:00'
end: '2025-11-14T11:30:00'
duration: 60min
project_uid: 135efa63
objective_uid: 3a986ba1
area_uid: 74a241b3
acceptance_criteria:
- 完成标注
- 次日提交申请
deliverable: []
repeat_cycle: 不重复
created_at: '2025-10-27'
time_logs: []
completed_at: '2025-11-12T08:50:05'
time_spent_min: 0
