id: __6e46
uid: 6e4600f7
title: 开始投稿
status: todo
due: '2026-04-01'
start: '2026-04-01T08:00:00'
end: '2026-04-01T10:00:00'
duration: 2h
project_uid: 0df9eaf5
objective_uid: 4aacb7e6
area_uid: d5b88577
acceptance_criteria: []
deliverable: []
repeat_cycle: 不重复
created_at: '2026-01-10'
