id: __a30a
uid: a30a5e34
title: 科学内容一致性
status: done
due: '2026-01-12'
start: '2026-01-12T08:00:00'
end: '2026-01-12T10:00:00'
duration: 2h
project_uid: cd66fa1b
objective_uid: 56b6db08
area_uid: d5b88577
acceptance_criteria: []
deliverable: []
repeat_cycle: 不重复
created_at: '2026-01-09'
time_logs: []
completed_at: '2026-01-14T07:37:51'
time_spent_min: 0
