id: __a644
uid: a6447b37
title: 语言格式清扫
status: done
due: '2025-11-02'
start: '2025-11-02T09:30:00'
end: '2025-11-02T11:30:00'
duration: 2h
project_uid: 6a97c3dd
objective_uid: 5239c235
area_uid: d5b88577
acceptance_criteria: []
deliverable: []
repeat_cycle: 不重复
created_at: '2025-10-27'
time_logs: []
completed_at: '2025-11-04T08:12:34'
time_spent_min: 0
