uid: b35732c8
title: 数据准备与预处理
desc: "任务目标： 对原始转录组和脂质组数据进行规范化和转换处理，为后续机制分析奠定统一基础。\n具体步骤：\n收集KO组与WT组的转录组表达矩阵和脂质组定量数据，执行初步数据质控（剔除异常值等）。\n\
  对转录组数据做标准化处理（如库大小校正或CPM/RPKM标准化），确保不同样本之间表达量可比。\n对脂质组数据采用内部标准校正和批次校正：利用内标物调整各样本的总量差异，并在每个批次内应用稳健标准化方法（如“中位数-of-ratios”）平衡批间偏差
  。\n应用对数比（log-ratio）转换处理脂质组数据 ：优先采用加法闭合（ALR）或中心化（CLR）对数比方法，将脂质组成数据转换到Aitchison体系，以稳定的内参物或同类脂质组分作为分母，减少总量效应和批次差异造成的假相关。\n\
  确认所有后续分析所需的衍生指标（例如CL/PG比值等）都可从预处理后的数据中计算得到。\n"
status: done
due: '2025-11-18'
start: '2025-11-18T08:00:00'
end: '2025-11-18T12:00:00'
duration: 4h
project_uid: 81988ed4
objective_uid: ae37276e
area_uid: 74a241b3
acceptance_criteria:
- RNA-seq 原始测序数据处理管线——基因层面的标准化计数矩阵
- 获得规范化的转录组表达数据和经过log-ratio转换的脂质组数据矩阵，各批次数据差异已校正，为机制分析提供一致的数据输入。
deliverable: []
repeat_cycle: 不重复
created_at: '2025-10-21'
time_logs:
- start: '2025-11-05T07:33:06'
  end: '2025-11-05T10:08:46'
  note: "首先建立文件夹结构\n成功建立了micromaba管理的虚拟环境（因为要同时使用r和python）\n激活虚拟环境\n建立seq处理的基础脚本与配置文件——完成，之后完成处理后需要反过来检查这一部分是否完全符合要求\n\
    添加git追踪\n下载参考基因组，时间比较长——已完成\n跑第一遍基础处理，等待跑完\n\n\n\n"
- start: '2025-11-06T07:52:48'
  end: '2025-11-06T14:46:52'
  note: "目前正在对原始数据进行处理，输出差异基因\n目前需要检查，从原始数据到现在为止，数据处理是否都正确？如果问题定位在04比对过程，重新进行该过程\n\
    检查到目前的run all是batch1全部跑完再跑batch2，也就是说batch2/3的01、2、3还没跑，于是决定在内存设备更新前首先进行batch2、3的质量控制与剪切\n\
    在这期间，首先确定脂质组学数据的多组学分析计划\n建立基础脚本，进行测试性处理\n还是要每步都了解原理、跑通、检查\n首先将整个文件夹转移到apsf格式的固态硬盘中，再进行处理，可能会顺畅"
- start: '2025-11-07T07:16:41'
  end: '2025-11-08T15:22:46'
  note: "先确认04之前的步骤的原理，以及是否都产生了可用的文件，然后了解04的原理，重新设计脚本\n- 01产生的文件不完全，但是质量较高，将01缺的文件找出来，单独重新跑\n\
    - 跑完以后，再进行一次质量检测，没问题了再进下一步\n- 在这期间，看00脚本的质量与完整性测试——完整，质量较高\n- 获得01结果，重新进行质量与完整性策略——完整，质量较高\n\
    进行02的质量与完整性测试——完整，质量较高，命名有问题\n重新跑整个02，完成后再进行质量与完整性检测——未能完成，先把04跑起来吧\n完成00，参考基因，进行质量与完整性检测——完整，质量高\n\
    完成比对、计数和矩阵合并，接下来需要进行差异分析与可视化分析\n"
- start: '2025-11-11T08:03:06'
  end: '2025-11-12T15:41:15'
  note: "确定预期结果——完成\n确定批次统一方法\n发现批次间效应*批次交互显著，说明可能需要删除某批次数据——经统计并不显著，所以进到下一步脂质组数据处理"
- start: '2025-11-12T15:41:18'
  end: '2025-11-13T12:29:53'
  note: "脂质组数据基础处理\n首先了解我们的基础文件结构，对于后续是否有用\ngroup中的q列很重要，而第一次脂质组学中缺少该列，需要重新导出该列\n\
    确定文件合并策略\n将基础文件融合在一起，形成长表便于分析——放弃第一批的Q，完成\n\n"
- start: '2025-11-13T13:31:22'
  end: '2025-11-14T08:26:46'
  note: "将batch1的原始数据提取出来，与新数据进行比较数值是否相同，如果不同，说明经过处理；如果相同，说明未经过处理，选择使用原始数据即可\n确定现在的脂质组数据有没有经过处理——已经与黄河老师课题组人确认，只进行过去重与异常值剔除，所以我们可以替换batch1为原始文件，使用相同阈值的异常值矫正覆盖原本的去重与异常值剔除。\n\
    \n"
- start: '2025-11-14T08:26:54'
  end: '2025-11-15T12:09:31'
  note: "首先进行原始数据筛选\n原始数据筛选的步骤——已经完成筛选，接下来需要理解、整理筛选步骤后，根据步骤的逻辑验证筛选结果是否符合要求"
- start: '2025-11-15T12:09:37'
  end: '2025-11-15T12:17:25'
  note: "目前已经完成数据准备与预处理，接下来的步骤是先跑通整个过程（确定基因集、脂质集），然后考虑使用多批次数据还是使用单一批次数据（似乎为了获得正确的脂质结果，只能使用单一批次）确定目的，然后高速前进，获得想要的结果！\n"
- start: '2025-11-15T12:21:15'
  end: '2025-11-15T13:04:03'
  note: 首要事件是理清楚顺序
completed_at: '2025-11-17T10:41:27'
time_spent_min: 8487
